### ISSUE TITLE
Manual Mode: Temperature at 50°C after gateway restart

### ISSUE THREAD

**Issue by githtz** [diyless/opentherm-gateway-simple#4]
Hi, I am not sure if this is the place for this issue. If not, please point me in the right direction.

I am using my Diyless OpenTherm Thermostat for a few days now. I instantly upgraded to FW 1.6 once I started using it this monday. Today I think I found an issue regarding the manual boiler temperature mode.

When the device restarts for whatever reason, the manual mode temperature will be set to 50°C.

This can be easily reproduced by restarting it from the UI or powering it down and then up by un/plugging the cable.

For some reason it looked like the OpenTherm Thermostat restarted on its own though and afterwards the manual mode had been enabeld, but I could not reproduce that behavior.

**Comment by diyless** [comment]
Hi @githtz ,
Storing manual mode temperature will be fixed in the next thermostat firmware version.
Thanks,
DIYLESS
